version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack --mode production
artifacts:
  files:
    - index.html
    - favicon.ico
    - Vasishta_Adiraju.pdf
    - styles/main.css
    - images/*
    - images/profile.jpg
    - dist/bundle.js
