version: 0.1

phases:
  build:
    commands:
      - echo Nothing still in development
artifacts:
  files:
    - index.html
    - favicon.ico
    - Vasishta_Adiraju.pdf
    - styles/main.css
    - images/*
